import type {NextPage} from "next";
import Head from "next/head";
import Link from "next/link";
import Layout from "../components/layout";
import {RouterOutputs, trpc} from "../utils/trpc";
import {Error, Loading} from "../components/skeletons";
import React from "react";
import CollapsibleCard from "../components/collapsibleCard";

export type ComponentChildren = string | JSX.Element | JSX.Element[];

const Home: NextPage = () => {
  const {
    data: categories,
    isLoading,
    isError,
  } = trpc.categories.forCurrentUser.useQuery();

  if (isLoading) return <Loading />;
  if (isError) return <Error />;

  return (
    <>
      <Head>
        <title>Agora</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {categories.map(category => (
          <Category
            className="mb-4"
            key={category.title}
            category={category}></Category>
        ))}
      </Layout>
    </>
  );
};

export function Category({
  category,
  className = "",
}: {
  category: RouterOutputs["categories"]["forCurrentUser"][number];
  className?: string;
}) {
  return (
    <CollapsibleCard className={className}>
      <CollapsibleCard.CardHeader>
        <Link
          href={`/category/${category.href}`}
          className="mx-auto self-center text-xl font-bold">
          {category.title}
        </Link>
      </CollapsibleCard.CardHeader>
      <CollapsibleCard.CardContent>
        {category.subforums.map(subforum => (
          <div
            key={subforum.title}
            className="mb-0.5 w-full rounded-lg bg-slate-100 p-4 dark:bg-gray-900">
            <Link
              href={`/category/${subforum.href}`}
              className="text-xl font-semibold">
              {subforum.title}
            </Link>
            <p className="text-md">{subforum.description}</p>
            <ul className="flex flex-row gap-2">
              <li className="text-xs">
                Threads:{" "}
                <span className=" font-semibold">{subforum.threadsAmount}</span>
              </li>
              <li className="text-xs">
                Posts:{" "}
                <span className=" font-semibold">{subforum.postsAmount}</span>
              </li>
            </ul>
          </div>
        ))}
      </CollapsibleCard.CardContent>
    </CollapsibleCard>
  );
}

export default Home;
